(()=>{'use strict';
const DATA_KEY='cb_fixed_questions_v1',PROGRESS_KEY='cb_fixed_progress_v1',SETTINGS_KEY='cb_fixed_settings_v1';
const clone=v=>JSON.parse(JSON.stringify(v));
let questions=loadQuestions(),progress=JSON.parse(localStorage.getItem(PROGRESS_KEY)||'{}'),settings=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}');
let filtered=[],position=0,figureVisible=false,sourcePageVisible=false,answerVisible=false,mcqSelection=new Set(),editingId=null,pendingImage=null;
let selectedUnits=new Set(settings.units||CB_DEFAULT_DATA.units.map(u=>u.name));
let selectedImportance=new Set((settings.importance||['1','2','3']).map(String));
const $=id=>document.getElementById(id);
const els={resultCount:$('resultCount'),progressText:$('progressText'),progressFill:$('progressFill'),statNew:$('statNew'),statKnown:$('statKnown'),statUnknown:$('statUnknown'),status:$('statusFilter'),order:$('orderFilter'),search:$('searchInput'),unitBadge:$('unitBadge'),importanceBadge:$('importanceBadge'),card:$('studyCard'),empty:$('emptyState'),number:$('numberChip'),unit:$('unitChip'),importance:$('importanceChip'),source:$('sourceText'),question:$('questionText'),figureBtn:$('figureBtn'),figureBox:$('figureBox'),figure:$('figureImage'),sourcePageBtn:$('sourcePageBtn'),sourcePageBox:$('sourcePageBox'),sourcePageCaption:$('sourcePageCaption'),sourcePageImage:$('sourcePageImage'),mcq:$('mcqBox'),answerBtn:$('answerBtn'),answerBox:$('answerBox'),answer:$('answerText'),explanation:$('explanationText'),position:$('positionText')};
function loadQuestions(){try{const v=JSON.parse(localStorage.getItem(DATA_KEY));if(Array.isArray(v)&&v.length)return v}catch(e){}return clone(CB_DEFAULT_DATA.questions)}
function saveQuestions(){localStorage.setItem(DATA_KEY,JSON.stringify(questions))}function saveProgress(){localStorage.setItem(PROGRESS_KEY,JSON.stringify(progress))}function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify({units:[...selectedUnits],importance:[...selectedImportance],theme:document.body.classList.contains('dark')?'dark':'light'}))}
function stars(n){return '★'.repeat(Number(n))+'☆'.repeat(3-Number(n))}
function labelImportance(n){return `${stars(n)} ${CB_DEFAULT_DATA.importanceLabels[String(n)]}`}
function applyFilters(reset=true){const term=els.search.value.trim().toLowerCase(),status=els.status.value;filtered=questions.filter(q=>selectedUnits.has(q.unit)&&selectedImportance.has(String(q.importance))).filter(q=>{const s=progress[q.id]?.status||'new';return status==='all'||s===status}).filter(q=>!term||[q.question,q.answer,q.explanation,q.source,q.unit].join(' ').toLowerCase().includes(term));if(els.order.value==='shuffle')shuffle(filtered);else filtered.sort((a,b)=>(a.number||999999)-(b.number||999999));if(reset)position=0;else position=Math.max(0,Math.min(position,filtered.length-1));render();updateStats();}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}}
function resetCardState(){figureVisible=false;sourcePageVisible=false;answerVisible=false;mcqSelection=new Set();els.figureBox.classList.add('hidden');els.sourcePageBox.classList.add('hidden');els.answerBox.classList.add('hidden');els.answerBtn.textContent='解答を見る';els.mcq.innerHTML='';}
function render(){els.resultCount.textContent=`${filtered.length}問`;els.unitBadge.textContent=selectedUnits.size===CB_DEFAULT_DATA.units.length?'全9':selectedUnits.size;els.importanceBadge.textContent=selectedImportance.size===3?'全3':selectedImportance.size;if(!filtered.length){els.card.classList.add('hidden');els.empty.classList.remove('hidden');return}els.card.classList.remove('hidden');els.empty.classList.add('hidden');resetCardState();const q=filtered[position];els.number.textContent=q.number?`問${q.number}`:'追加問題';els.unit.textContent=q.unit;els.importance.textContent=labelImportance(q.importance);els.importance.dataset.level=q.importance;els.source.textContent=q.source?`出典：${q.source}`:'';els.question.textContent=q.question;els.position.textContent=`${position+1} / ${filtered.length}`;els.answer.textContent=q.type==='mcq'?q.correct.map(k=>`${k} ${q.options.find(o=>o.key===k)?.text||''}`).join(' ／ '):q.answer;els.explanation.textContent=q.explanation||'解説は未設定です。';if(q.image||q.imageData){els.figureBtn.classList.remove('hidden');els.figure.src=q.imageData||('./'+q.image);els.figureBtn.textContent='図・写真を表示'}else{els.figureBtn.classList.add('hidden');els.figure.removeAttribute('src')}if(q.sourcePages&&q.sourcePages.length){els.sourcePageBtn.classList.remove('hidden');const first=q.sourcePages[0];els.sourcePageCaption.textContent=`${first.label} を表示`;els.sourcePageImage.src='./'+first.path;els.sourcePageBtn.textContent='対応資料ページを表示'}else{els.sourcePageBtn.classList.add('hidden');els.sourcePageImage.removeAttribute('src');els.sourcePageCaption.textContent=''}if(q.type==='mcq'){els.mcq.classList.remove('hidden');q.options.forEach(o=>{const lab=document.createElement('label');lab.className='option';lab.dataset.key=o.key;lab.innerHTML=`<input type="${q.correct.length>1?'checkbox':'radio'}" name="mcq" value="${o.key}"><strong>${o.key}</strong><span>${escapeHtml(o.text)}</span>`;lab.querySelector('input').addEventListener('change',e=>{if(q.correct.length===1)mcqSelection.clear();if(e.target.checked)mcqSelection.add(o.key);else mcqSelection.delete(o.key)});els.mcq.appendChild(lab)})}else els.mcq.classList.add('hidden');updateJudgeButtons(q.id)}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showAnswer(){if(!filtered.length)return;answerVisible=!answerVisible;els.answerBox.classList.toggle('hidden',!answerVisible);els.answerBtn.textContent=answerVisible?'解答を隠す':'解答を見る';if(answerVisible&&filtered[position].type==='mcq'){const correct=new Set(filtered[position].correct);els.mcq.querySelectorAll('.option').forEach(el=>{const key=el.dataset.key;el.classList.toggle('correct',correct.has(key));el.classList.toggle('wrong',mcqSelection.has(key)&&!correct.has(key))})}}
function toggleFigure(){figureVisible=!figureVisible;els.figureBox.classList.toggle('hidden',!figureVisible);els.figureBtn.textContent=figureVisible?'図・写真を隠す':'図・写真を表示'}
function toggleSourcePage(){sourcePageVisible=!sourcePageVisible;els.sourcePageBox.classList.toggle('hidden',!sourcePageVisible);els.sourcePageBtn.textContent=sourcePageVisible?'対応資料ページを隠す':'対応資料ページを表示'}
function move(delta){if(!filtered.length)return;position=(position+delta+filtered.length)%filtered.length;render();window.scrollTo({top:0,behavior:'smooth'})}
function mark(status){const q=filtered[position];progress[q.id]={status,updatedAt:new Date().toISOString()};saveProgress();updateJudgeButtons(q.id);updateStats();setTimeout(()=>move(1),180)}
function updateJudgeButtons(id){const s=progress[id]?.status;$('knownBtn').classList.toggle('active',s==='known');$('unknownBtn').classList.toggle('active',s==='unknown')}
function updateStats(){let known=0,unknown=0;questions.forEach(q=>{const s=progress[q.id]?.status;if(s==='known')known++;if(s==='unknown')unknown++});const learned=known+unknown,total=questions.length;els.statKnown.textContent=known;els.statUnknown.textContent=unknown;els.statNew.textContent=total-learned;els.progressText.textContent=`学習状況 ${learned} / ${total}`;els.progressFill.style.width=total?`${learned/total*100}%`:'0%'}
function openCheck(kind){const isUnit=kind==='unit',dialog=$('checkDialog');$('checkTitle').textContent=isUnit?'出題する単元':'出題する重要度';const list=$('checkList');list.innerHTML='';const entries=isUnit?CB_DEFAULT_DATA.units.map(u=>[u.name,u.name]):[['3','★★★ 最重要'],['2','★★ 重要'],['1','★ 補足']];entries.forEach(([value,label])=>{const row=document.createElement('label');row.className='check-item';const checked=isUnit?selectedUnits.has(value):selectedImportance.has(value);row.innerHTML=`<input type="checkbox" value="${escapeHtml(value)}" ${checked?'checked':''}><span>${escapeHtml(label)}</span>`;list.appendChild(row)});dialog.dataset.kind=kind;dialog.showModal()}
$('checkDialog').addEventListener('close',()=>{if($('checkDialog').returnValue!=='apply')return;const vals=[...$('checkList').querySelectorAll('input:checked')].map(x=>x.value);if(!vals.length){toast('少なくとも1つ選択してください');return}if($('checkDialog').dataset.kind==='unit')selectedUnits=new Set(vals);else selectedImportance=new Set(vals);saveSettings();applyFilters()});
$('selectAllBtn').onclick=()=>$('checkList').querySelectorAll('input').forEach(x=>x.checked=true);$('clearAllBtn').onclick=()=>$('checkList').querySelectorAll('input').forEach(x=>x.checked=false);
function showSummaries(){const box=$('summaryContent');box.innerHTML='';const units=CB_DEFAULT_DATA.units.filter(u=>selectedUnits.has(u.name));units.forEach(u=>{const sec=document.createElement('section');sec.className='summary-unit';sec.innerHTML=`<h3>${escapeHtml(u.name)}</h3><ul>${u.summary.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul>`;box.appendChild(sec)});$('summaryDialog').showModal()}
function openEdit(mode){editingId=mode==='add'?null:filtered[position]?.id;pendingImage=null;const q=editingId?questions.find(x=>x.id===editingId):{unit:[...selectedUnits][0]||CB_DEFAULT_DATA.units[0].name,importance:2,type:'short',question:'',answer:'',explanation:'',source:'',options:[],correct:[],image:null,imageData:null};$('editTitle').textContent=editingId?'問題を編集':'問題を追加';$('editUnit').innerHTML=CB_DEFAULT_DATA.units.map(u=>`<option>${escapeHtml(u.name)}</option>`).join('');$('editUnit').value=q.unit;$('editImportance').value=String(q.importance);$('editType').value=q.type;$('editQuestion').value=q.question;$('editAnswer').value=q.answer||'';$('editExplanation').value=q.explanation||'';$('editSource').value=q.source||'';$('editOptions').value=(q.options||[]).map(o=>`${o.key} ${o.text}`).join('\n');$('editCorrect').value=(q.correct||[]).join(',');$('currentImageText').textContent=(q.image||q.imageData)?'画像あり':'画像なし';$('editImageFile').value='';toggleEditFields();$('editDialog').showModal()}
function toggleEditFields(){const mcq=$('editType').value==='mcq';$('shortFields').classList.toggle('hidden',mcq);$('mcqFields').classList.toggle('hidden',!mcq)}
$('editType').onchange=toggleEditFields;$('editImageFile').onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>900000){toast('画像は900KB以下にしてください');e.target.value='';return}const r=new FileReader();r.onload=()=>{pendingImage=r.result;$('currentImageText').textContent=`新しい画像：${f.name}`};r.readAsDataURL(f)};
$('removeImageBtn').onclick=()=>{pendingImage='REMOVE';$('currentImageText').textContent='保存時に画像を外します'};
$('editForm').onsubmit=e=>{e.preventDefault();const type=$('editType').value;let options=[],correct=[];if(type==='mcq'){options=$('editOptions').value.split(/\n/).map(x=>x.trim()).filter(Boolean).map((x,i)=>{const m=x.match(/^([a-zA-Z])\s*[\.．:]?\s*(.+)$/);return m?{key:m[1].toLowerCase(),text:m[2]}:{key:String.fromCharCode(97+i),text:x}});correct=$('editCorrect').value.toLowerCase().split(/[,、\s]+/).filter(Boolean);if(!options.length||!correct.length){toast('選択肢と正解記号を入力してください');return}}const existing=editingId?questions.find(x=>x.id===editingId):null;const maxNum=Math.max(0,...questions.map(x=>Number(x.number)||0));const q=existing||{id:'custom_'+Date.now(),number:maxNum+1,custom:true};Object.assign(q,{unit:$('editUnit').value,importance:Number($('editImportance').value),type,question:$('editQuestion').value.trim(),answer:type==='short'?$('editAnswer').value.trim():correct.join('・'),explanation:$('editExplanation').value.trim(),source:$('editSource').value.trim(),options,correct});if(pendingImage==='REMOVE'){q.image=null;q.imageData=null}else if(pendingImage){q.image=null;q.imageData=pendingImage}if(!existing)questions.push(q);saveQuestions();$('editDialog').close();applyFilters(false);const i=filtered.findIndex(x=>x.id===q.id);if(i>=0)position=i;render();toast(existing?'問題を更新しました':'問題を追加しました')};
function deleteCurrent(){if(!filtered.length)return;const q=filtered[position];if(!confirm(`「${q.question.slice(0,40)}」を削除しますか？`))return;questions=questions.filter(x=>x.id!==q.id);delete progress[q.id];saveQuestions();saveProgress();applyFilters(false);toast('問題を削除しました')}
function exportBackup(){const obj={app:'固定性補綴学 暗記アプリ',version:1,exportedAt:new Date().toISOString(),questions,progress,settings:{units:[...selectedUnits],importance:[...selectedImportance],theme:document.body.classList.contains('dark')?'dark':'light'}};const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`固定性補綴学_バックアップ_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
$('importInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const obj=JSON.parse(await f.text());if(!Array.isArray(obj.questions))throw Error();questions=obj.questions;progress=obj.progress||{};selectedUnits=new Set(obj.settings?.units||CB_DEFAULT_DATA.units.map(u=>u.name));selectedImportance=new Set((obj.settings?.importance||['1','2','3']).map(String));saveQuestions();saveProgress();saveSettings();applyFilters();toast('バックアップを読み込みました')}catch(err){toast('読み込めないバックアップです')}e.target.value=''};
function resetData(){if(!confirm('編集・追加した問題を削除し、初期326問へ戻しますか？\n学習状況は残ります。'))return;questions=clone(CB_DEFAULT_DATA.questions);saveQuestions();applyFilters();toast('初期問題へ戻しました')}
function resetFilters(){selectedUnits=new Set(CB_DEFAULT_DATA.units.map(u=>u.name));selectedImportance=new Set(['1','2','3']);els.status.value='all';els.order.value='number';els.search.value='';saveSettings();applyFilters()}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.add('hidden'),2200)}
$('answerBtn').onclick=showAnswer;$('figureBtn').onclick=toggleFigure;$('sourcePageBtn').onclick=toggleSourcePage;$('prevBtn').onclick=()=>move(-1);$('nextBtn').onclick=()=>move(1);$('knownBtn').onclick=()=>mark('known');$('unknownBtn').onclick=()=>mark('unknown');$('unitFilterBtn').onclick=()=>openCheck('unit');$('importanceFilterBtn').onclick=()=>openCheck('importance');$('summaryBtn').onclick=showSummaries;$('resetFiltersBtn').onclick=resetFilters;els.status.onchange=()=>applyFilters();els.order.onchange=()=>applyFilters();els.search.oninput=()=>applyFilters();$('editBtn').onclick=()=>openEdit('edit');$('addBtn').onclick=()=>openEdit('add');$('deleteBtn').onclick=deleteCurrent;$('exportBtn').onclick=exportBackup;$('resetDataBtn').onclick=resetData;$('closeEditBtn').onclick=$('cancelEditBtn').onclick=()=>$('editDialog').close();
$('themeBtn').onclick=()=>{document.body.classList.toggle('dark');saveSettings()};if(settings.theme==='dark')document.body.classList.add('dark');
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
applyFilters();})();